AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-connect-interactive-messages
    Description: Creates AWS Lambda function to be used as an initialization and validation code hook in Amazon Lex Bot for enabling interactive messages in Amazon Connect Chat.
    Author: Amazon Connect CX Innovations
    SpdxLicenseId: MIT-0
    Labels: ['connect', 'chat', 'interactive-messaging', 'contact-center', 'lambda', 'lex', 'bot']
    SemanticVersion: 0.0.1

Mappings:
  FunctionMap:
    Configuration:
      S3Bucket: "start-chat-contact-api-cfn"
      S3Key: "deployment/"
      SolutionID: "AC0002"

Parameters:
  contactFlowId:
    Type: String
    Default: 12345678-1234-1234-1234-123456789012
    Description: The contact flow id that the customer will interact with while chatting
    AllowedPattern: '\w{8}-\w{4}-\w{4}-\w{4}-\w{12}'
  instanceId:
    Type: String
    Default: 12345678-1234-1234-1234-123456789012
    Description: The instance id of the Amazon Connect instance that the customer will interact with while chatting
    AllowedPattern: '\w{8}-\w{4}-\w{4}-\w{4}-\w{12}'
  allowAnonymousUsageMetrics:
    Type: String
    Default: "No"
    AllowedValues:
      - "Yes"
      - "No"
    Description: Send usage metrics about this CloudFormation stack to AWS

Globals:
  Function:
    Timeout: 3
  Api:
    BinaryMediaTypes:
      # The ~1 will be replaced with / when deployed
      - '*~1*'
Resources:

  
  #### Lambda #####
  ChatSDKLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - "nodejs10.x"
        - "nodejs8.10"
      Content:
        S3Bucket:
          !Join
            - '.'
            - - !Ref 'AWS::Region'
              - !FindInMap [FunctionMap, Configuration, S3Bucket]
        S3Key: !Join ["", [!FindInMap [FunctionMap, Configuration, S3Key], 'ChatSDK.zip']]
      Description: The AWS SDK including Amazon Connect Chat APIs.

  #### Custom AWS Connect Lambda ####
  AWSConnectLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Description:  Custom AWS Lambda Function
      Handler: src/customConnectLambda.handler
      Role: !GetAtt AWSConnectLambdaExecutionRole.Arn
      Runtime: "nodejs10.x"
      MemorySize: 128
      Timeout: 10
      Layers:
        - !Ref ChatSDKLayer
      Environment:
        Variables:
          INSTANCE_ID: !Ref instanceId
          CONTACT_FLOW_ID: !Ref contactFlowId
          SOLUTION_ID: !FindInMap [FunctionMap, Configuration, SolutionID]
  AWSConnectLambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: start-chat-contact-execution-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - Effect: "Allow"
                Action:
                  - "connect:StartChatContact"
                Resource:
                  - !Sub "arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/${instanceId}"
                  - !Sub "arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/${instanceId}/*"

  StartChatLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Description:  AWS Lambda Function to initiate the chat with the end user
      Handler: "src/awsConnectHandler/startChatContact.handler"
      Role: !GetAtt StartChatLambdaExecutionRole.Arn
      Runtime: "nodejs10.x"
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref ChatSDKLayer
      Environment:
        Variables:
          INSTANCE_ID: !Ref instanceId
          CONTACT_FLOW_ID: !Ref contactFlowId
          SOLUTION_ID: !FindInMap [FunctionMap, Configuration, SolutionID]
      Code:
        S3Bucket:
          !Join
            - '.'
            - - !Ref 'AWS::Region'
              - !FindInMap [FunctionMap, Configuration, S3Bucket]
        S3Key: !Join ["", [!FindInMap [FunctionMap, Configuration, S3Key], 'start-chat-contact.zip']]

  StartChatLambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: start-chat-contact-execution-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - Effect: "Allow"
                Action:
                  - "connect:StartChatContact"
                Resource:
                  - !Sub "arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/${instanceId}"
                  - !Sub "arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/${instanceId}/*"

  #### API Gateway ##### https://blog.jayway.com/2016/08/17/introduction-to-cloudformation-for-api-gateway/
  # CORS: https://bitbucket.org/snippets/spenser_filler/LenB4p
  ApiGatewayRestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "StartChatContact"
      Description: "API to initiate chat with Amazon Connect"

  LambdaApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt StartChatLambda.Arn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestAPI}/*"

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayRootMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestAPI
      StageName: "Prod"

  ApiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: LambdaApiGatewayInvokePermission
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "POST"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt StartChatLambda.Arn
        PassthroughBehavior: WHEN_NO_MATCH
      ResourceId:  !GetAtt ApiGatewayRestAPI.RootResourceId
      RestApiId: !Ref ApiGatewayRestAPI
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: Empty
        - StatusCode: "500"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          ResponseModels:
            application/json: Empty

  ApiGatewayOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !GetAtt ApiGatewayRestAPI.RootResourceId
      RestApiId: !Ref ApiGatewayRestAPI
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        Type: MOCK
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: >-
                'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
              method.response.header.Access-Control-Allow-Methods: '''POST,OPTIONS'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
            ResponseTemplates:
              application/json: ''
            StatusCode: '200'
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
          StatusCode: '200'

#Original Code for working bot
  InteractiveMessagingLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: React TodoMVC with a Serverless backend
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: build/todo.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: todoTable
      Timeout: 5
      Events:
        root:
          Type: Api
          Properties:
            Path: /prod
            Method: get
        getProxy:
          Type: Api
          Properties:
            Path: '/prod/{proxy+}'
            Method: get
        postProxy:
          Type: Api
          Properties:
            Path: '/prod/{proxy+}'
            Method: post
        apiPost:
          Type: Api
          Properties:
            Path: /api
            Method: post
      Environment:
        Variables:
          TABLE:
            Ref: todoTable
      
  todoTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  InteractiveMessagingLambdaFunction:
    Description: "Interactive Messaging Lex Lambda Function ARN"
    Value: !GetAtt InteractiveMessagingLambdaFunction.Arn
  InteractiveMessagingFunctionIamRole:
    Description: "Implicit IAM Role created for Interactive Messaging Lex Lambda Function"
    Value: !GetAtt InteractiveMessagingLambdaFunctionRole.Arn